@server = http://localhost:3000

# 게시글 조회
GET {{server}}/blog

### 게시글 생성
POST {{server}}/blog
Content-Type: application/json

{
    "title": "Hello",
    "content": "Nice to meet you",
    "name": "Test"
}

### 특정 게시글 조회
GET {{server}}/blog/2

###게시글 삭제
DELETE {{server}}/blog/64c3391d9d1bc67094583b25

###게시글 수정
PUT {{server}}/blog/2
Content-Type: application/json

{
    "title": "타이틀 수정",
    "content": "본문 수정",
    "name": "json"
}